"""
Chat API routes – the primary inference endpoints.

POST /v1/chat        – full response (non-streaming)
POST /v1/chat/stream – SSE token streaming
WS   /v1/ws/{session_id} – WebSocket bidirectional
"""
from __future__ import annotations

import asyncio
import json
import time
from typing import AsyncGenerator

from fastapi import APIRouter, Depends, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse

from orchestrator.core.types import (
    ChatRequest,
    ChatResponse,
    GenerationParams,
    MessageRole,
    Message,
    StreamEventType,
)
from orchestrator.core.exceptions import LlamaServerError, LlamaTimeoutError, OrchestratorError
from orchestrator.runtime.inference_engine import InferenceEngine
from orchestrator.streaming.token_streamer import TokenStreamer
from orchestrator.streaming.websocket_manager import WebSocketManager
from orchestrator.utils.logging_utils import get_logger, bind_request_context

from orchestrator.api.dependencies import get_inference_engine, get_ws_manager

log = get_logger(__name__)
router = APIRouter(prefix="/v1", tags=["chat"])


@router.post("/chat", response_model=ChatResponse)
async def chat_endpoint(
    request: ChatRequest,
    engine: InferenceEngine = Depends(get_inference_engine),
) -> ChatResponse:
    """
    Full-response chat endpoint.
    Runs the full orchestration pipeline and returns when generation is finished.
    """
    try:
        return await engine.process_request(request)
    except LlamaTimeoutError as exc:
        raise HTTPException(status_code=504, detail="LLM inference timed out") from exc
    except LlamaServerError as exc:
        raise HTTPException(status_code=502, detail=f"LLM backend error: {exc.message}") from exc
    except OrchestratorError as exc:
        raise HTTPException(status_code=500, detail=exc.message) from exc


@router.post("/chat/stream")
async def chat_stream_endpoint(
    request: ChatRequest,
    engine: InferenceEngine = Depends(get_inference_engine),
) -> StreamingResponse:
    """
    Server-Sent Events streaming endpoint.
    Streams tokens as they are generated by TinyLlama.

    Event format:
        data: {"event_type": "token", "content": "Hello", "done": false}
        data: {"event_type": "done", "done": true, "metadata": {...}}
    """
    session_id = request.session_id
    query = request.last_user_message

    async def event_stream() -> AsyncGenerator[str, None]:
        try:
            # Run the orchestration pipeline up to and including fusion
            intent = await engine._classifier.classify(query)
            decision = engine._router.route(intent)
            stored_conv = await engine._memory.get_conversation(session_id)

            # Merge in-request history then append current user message
            request_history = [m for m in request.messages[:-1]]
            if request_history:
                seen = {m.content for m in stored_conv}
                for m in request_history:
                    if m.content not in seen:
                        stored_conv.append(m)
            from orchestrator.core.types import MessageRole
            stored_conv.append(Message(role=MessageRole.USER, content=query))
            conversation = stored_conv

            from orchestrator.utils.async_utils import gather_with_fallback
            from orchestrator.runtime.inference_engine import _empty_rag_result, _empty_memory_result
            from orchestrator.runtime.inference_engine import _empty_rag

            memory_context = f"{query}\n" + " ".join(m.content for m in conversation[-5:-1])
            memory_result, rag_result, expert_guidance = await gather_with_fallback(
                engine._memory.retrieve_all(memory_context, session_id),
                engine._rag.retrieve(query) if decision.run_rag else _empty_rag(),
                engine._experts.get_guidance(query, intent, decision.active_experts),
                fallbacks=[_empty_memory_result(), _empty_rag_result(), None],
            )

            from orchestrator.core.types import MemoryResult
            if not isinstance(memory_result, MemoryResult):
                memory_result = _empty_memory_result()

            fused = await engine._fusion.fuse(
                query=query,
                intent=intent,
                memory_result=memory_result,
                rag_result=rag_result,
                expert_guidance=expert_guidance,
                conversation=conversation,
                system_prompt=decision.system_prompt_hint,
            )

            gen_params = engine._compute.optimize(
                intent=intent,
                fused_context=fused,
                base_params=decision.generation_override,
            )

            # Stream tokens
            streamer = TokenStreamer(session_id=session_id)
            full_content = []

            async for event in streamer.stream(engine.stream(fused, gen_params)):
                payload = json.dumps(event.model_dump())
                yield f"data: {payload}\n\n"

                if event.event_type == StreamEventType.TOKEN:
                    full_content.append(event.content)

            # Background memory update
            user_msg = Message(role=MessageRole.USER, content=query)
            asst_msg = Message(role=MessageRole.ASSISTANT, content="".join(full_content))
            asyncio.create_task(engine._memory.record_turn(session_id, user_msg, asst_msg))

        except Exception as exc:
            log.error("SSE stream error", error=str(exc))
            error_event = json.dumps({"event_type": "error", "content": str(exc), "done": True})
            yield f"data: {error_event}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.websocket("/ws/{session_id}")
async def websocket_endpoint(
    websocket: WebSocket,
    session_id: str,
    engine: InferenceEngine = Depends(get_inference_engine),
    ws_manager: WebSocketManager = Depends(get_ws_manager),
) -> None:
    """
    WebSocket endpoint for bidirectional streaming.

    Client sends:
        {"messages": [...], "stream": true}

    Server sends token-by-token:
        {"event_type": "token", "content": "Hello", "done": false}
        {"event_type": "done", "done": true, "metadata": {...}}
    """
    await ws_manager.connect(websocket, session_id)
    bind_request_context(session_id)

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                await ws_manager.send_error(session_id, "Invalid JSON")
                continue

            request = ChatRequest(
                session_id=session_id,
                messages=[
                    Message(role=MessageRole(m["role"]), content=m["content"])
                    for m in data.get("messages", [])
                ],
                stream=True,
            )

            query = request.last_user_message
            if not query:
                continue

            intent = await engine._classifier.classify(query)
            decision = engine._router.route(intent)
            conversation = await engine._memory.get_conversation(session_id)

            from orchestrator.core.types import MemoryResult
            from orchestrator.runtime.inference_engine import _empty_rag_result

            memory_result = MemoryResult(items=[], total_tokens=0, levels_queried=[], query_time_ms=0)
            try:
                memory_result = await engine._memory.retrieve_all(query, session_id)
            except Exception:
                pass

            rag_result = _empty_rag_result()
            if decision.run_rag:
                try:
                    rag_result = await engine._rag.retrieve(query)
                except Exception:
                    pass

            expert_guidance = None
            try:
                expert_guidance = await engine._experts.get_guidance(
                    query, intent, decision.active_experts
                )
            except Exception:
                pass

            fused = await engine._fusion.fuse(
                query=query,
                intent=intent,
                memory_result=memory_result,
                rag_result=rag_result,
                expert_guidance=expert_guidance,
                conversation=conversation,
                system_prompt=decision.system_prompt_hint,
            )

            gen_params = engine._compute.optimize(
                intent=intent,
                fused_context=fused,
                base_params=decision.generation_override,
            )

            full_content: list = []
            streamer = TokenStreamer(session_id=session_id)

            async for event in streamer.stream(engine.stream(fused, gen_params)):
                await ws_manager.send_event(session_id, event)
                if event.event_type == StreamEventType.TOKEN:
                    full_content.append(event.content)

            user_msg = Message(role=MessageRole.USER, content=query)
            asst_msg = Message(role=MessageRole.ASSISTANT, content="".join(full_content))
            asyncio.create_task(engine._memory.record_turn(session_id, user_msg, asst_msg))

    except WebSocketDisconnect:
        log.debug("WebSocket client disconnected", session=session_id)
    except Exception as exc:
        log.error("WebSocket error", session=session_id, error=str(exc))
        try:
            await ws_manager.send_error(session_id, str(exc))
        except Exception:
            pass
    finally:
        await ws_manager.disconnect(websocket, session_id)
