"""
Chat API routes – the primary inference endpoints.

POST /v1/chat        – full response (non-streaming)
POST /v1/chat/stream – SSE token streaming
WS   /v1/ws/{session_id} – WebSocket bidirectional
"""
from __future__ import annotations

import asyncio
import json
import time
from typing import AsyncGenerator

from fastapi import APIRouter, Depends, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.responses import StreamingResponse

from orchestrator.core.types import (
    ChatRequest,
    ChatResponse,
    GenerationParams,
    MessageRole,
    Message,
    StreamEventType,
)
from orchestrator.core.exceptions import LlamaServerError, LlamaTimeoutError, OrchestratorError
from orchestrator.runtime.inference_engine import InferenceEngine
from orchestrator.agents.multi_agent_engine import MultiAgentEngine
from orchestrator.streaming.token_streamer import TokenStreamer
from orchestrator.streaming.websocket_manager import WebSocketManager
from orchestrator.utils.logging_utils import get_logger, bind_request_context

from orchestrator.api.dependencies import get_inference_engine, get_multi_agent_engine, get_ws_manager

log = get_logger(__name__)
router = APIRouter(prefix="/v1", tags=["chat"])


@router.post("/chat", response_model=ChatResponse)
async def chat_endpoint(
    request: ChatRequest,
    engine: MultiAgentEngine = Depends(get_multi_agent_engine),
) -> ChatResponse:
    """
    Full-response chat endpoint.
    Complex queries are automatically decomposed and executed via the multi-agent
    system; simple queries are forwarded directly to InferenceEngine.
    """
    try:
        return await engine.process_request(request)
    except LlamaTimeoutError as exc:
        raise HTTPException(status_code=504, detail="LLM inference timed out") from exc
    except LlamaServerError as exc:
        raise HTTPException(status_code=502, detail=f"LLM backend error: {exc.message}") from exc
    except OrchestratorError as exc:
        raise HTTPException(status_code=500, detail=exc.message) from exc


@router.post("/chat/stream")
async def chat_stream_endpoint(
    request: ChatRequest,
    engine: InferenceEngine = Depends(get_inference_engine),
) -> StreamingResponse:
    """
    Server-Sent Events streaming endpoint.
    Streams tokens as they are generated by TinyLlama.

    Event format:
        data: {"event_type": "token", "content": "Hello", "done": false}
        data: {"event_type": "done", "done": true, "metadata": {...}}
    """
    session_id = request.session_id
    query = request.last_user_message

    async def event_stream() -> AsyncGenerator[str, None]:
        try:
            plan = await engine.build_generation_plan(request)
            streamer = TokenStreamer(session_id=session_id)
            full_content = []

            async for event in streamer.stream(engine.stream(plan.fused, plan.params)):
                yield f"data: {json.dumps(event.model_dump())}\n\n"
                if event.event_type == StreamEventType.TOKEN:
                    full_content.append(event.content)

            user_msg = Message(role=MessageRole.USER, content=query)
            asst_msg = Message(role=MessageRole.ASSISTANT, content="".join(full_content))
            asyncio.create_task(engine._memory.record_turn(session_id, user_msg, asst_msg))

        except Exception as exc:
            log.error("SSE stream error", error=str(exc))
            error_event = json.dumps({"event_type": "error", "content": str(exc), "done": True})
            yield f"data: {error_event}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.websocket("/ws/{session_id}")
async def websocket_endpoint(
    websocket: WebSocket,
    session_id: str,
    engine: InferenceEngine = Depends(get_inference_engine),
    ws_manager: WebSocketManager = Depends(get_ws_manager),
) -> None:
    """
    WebSocket endpoint for bidirectional streaming.

    Client sends:
        {"messages": [...], "stream": true}

    Server sends token-by-token:
        {"event_type": "token", "content": "Hello", "done": false}
        {"event_type": "done", "done": true, "metadata": {...}}
    """
    await ws_manager.connect(websocket, session_id)
    bind_request_context(session_id)

    try:
        while True:
            raw = await websocket.receive_text()
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                await ws_manager.send_error(session_id, "Invalid JSON")
                continue

            def _safe_role(raw: str) -> MessageRole:
                try:
                    return MessageRole(raw)
                except ValueError:
                    return MessageRole.USER

            request = ChatRequest(
                session_id=session_id,
                messages=[
                    Message(role=_safe_role(m.get("role", "user")), content=m.get("content", ""))
                    for m in data.get("messages", [])
                ],
                stream=True,
            )

            query = request.last_user_message
            if not query:
                continue

            plan = await engine.build_generation_plan(request)
            full_content: list = []
            streamer = TokenStreamer(session_id=session_id)

            async for event in streamer.stream(engine.stream(plan.fused, plan.params)):
                await ws_manager.send_event(session_id, event)
                if event.event_type == StreamEventType.TOKEN:
                    full_content.append(event.content)

            user_msg = Message(role=MessageRole.USER, content=query)
            asst_msg = Message(role=MessageRole.ASSISTANT, content="".join(full_content))
            asyncio.create_task(engine._memory.record_turn(session_id, user_msg, asst_msg))

    except WebSocketDisconnect:
        log.debug("WebSocket client disconnected", session=session_id)
    except Exception as exc:
        log.error("WebSocket error", session=session_id, error=str(exc))
        try:
            await ws_manager.send_error(session_id, str(exc))
        except Exception:
            pass
    finally:
        await ws_manager.disconnect(websocket, session_id)
